name: Update Combined Filter

on:
  schedule:
    - cron: '0 0 * * *' # 每天 UTC 00:00 執行
  workflow_dispatch: # 允許手動點擊按鈕觸發

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run update script
        run: python update_filter.py

      - name: Commit and Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add my_combined_list.txt
          git commit -m "Update filter list: $(date)" || exit 0
          git push
